language: perl
perl:
	- "5.8"
	- "5.10"
	- "5.12"
	- "5.14"
	- "5.16"
	- "5.18"
    - "5.20"

install:
    - cpanm --quiet --installdeps --notest . 
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls

script:
    - cover -delete && cover -test

after_success:
    - cover -report coveralls
