name: macos

on:
    push:
        branches:
            - '**'
            - '!**linux**'
            - '!**windows**'
        tags-ignore:
            # I tag release pushes but those should have already been tested
            - 'release-*'
        paths-ignore:
            # list all the files which are irrelevant to the tests
            # non-code, support files, docs, etc
            - '.appveyor.yml'
            - '.github/workflows/macos.yml'
            - '.github/workflows/ubuntu.yml'
            - '.gitignore'
            - '.releaserc'
            - 'Changes'
            - 'LICENSE'
            - 'README.pod'
        pull_request:

jobs:
    perl:
        runs-on: macOS-latest

        steps:
            - uses: actions/checkout@v2
            - name: Platform check
              run: uname -a
            - name: Set up Perl
              run: |
                brew install perl
                ls -d /usr/local/Cellar/perl/*/bin | head -1 >> $GITHUB_PATH
                perl -v | perl -0777 -ne 'm/(v5\.\d+)/ && print "PERL_VERSION=$1"' >> $GITHUB_ENV
            - name: Perl version check
              run: perl -V
            - name: Prepare cpan
              run: |
                openssl version
                cpan -M http://www.cpan.org -T IO::Socket::SSL LWP::Protocol::https
                cpan -M https://www.cpan.org -T ExtUtils::MakeMaker
            - name: Install dependencies
              run: |
                cpan -M https://www.cpan.org -T .
            - name: Run tests
              run: |
                perl Makefile.PL
                make test
            - name: Run tests in parallel
              run: |
                perl Makefile.PL
                HARNESS_OPTIONS=j10 make test
            - name: Run dist tests
              run: |
                perl Makefile.PL
                make disttest
